/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CartBar: typeof import('./src/components/ShoppingCart/CartBar.vue')['default']
    CartCard: typeof import('./src/components/ShoppingCart/CartCard.vue')['default']
    CartCheckoutCard: typeof import('./src/components/ShoppingCart/CartCheckoutCard.vue')['default']
    CouponCard: typeof import('./src/components/CouponCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCascader: typeof import('@nutui/nutui-taro')['Cascader']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutOverlay: typeof import('@nutui/nutui-taro')['Overlay']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    OrderCard: typeof import('./src/components/OrderCard.vue')['default']
    PointStoreItemCard: typeof import('./src/components/PointStoreItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopCard: typeof import('./src/components/ShopCard.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
  }
}
